export const Images = {
    mainIcon: require("../public/assets/AXC.svg"),
    bellIcon: require("../public/assets/bell.svg"),
    settingIcon: require("../public/assets/setting.svg"),
    worldIcon: require("../public/assets/world.svg"),
    innerGlobe: require("../public/assets/innerGlobe.svg"),
    outerGlobe: require("../public/assets/outerGlobe.svg"),
    lines: require("../public/assets/lines.svg"),
    mercury: require("../public/assets/mercury.svg"),
    facebook: require("../public/assets/facebook.svg"),
    twitter: require("../public/assets/twitter.svg"),
    google: require("../public/assets/google.svg"),
    youtube: require("../public/assets/youtube.svg"),
    question: require("../public/assets/question.svg"),
    first: require("../public/assets/1st.svg"),
    second: require("../public/assets/second.svg"),
    third: require("../public/assets/third.svg"),
    purchaseGlobe: require("../public/assets/purchaseglobe.svg"),
    dolphin: require("../public/assets/dolphin.svg"),
    tick: require("../public/assets/tick.svg"),
    mainQuestionMark: require("../public/assets/mainQuestionMark.svg"),
  };
  