export const Images = {
    mainIcon: require("../public/assets/AXC.svg"),
    bellIcon: require("../public/assets/bellIcon.svg"),
    settingIcon: require("../public/assets/setting.svg"),
    worldIcon: require("../public/assets/world.svg"),
    innerGlobe: require("../public/assets/innerGlobe.svg"),
    outerGlobe: require("../public/assets/outerGlobe.svg"),
    lines: require("../public/assets/lines.jpg"),
    coins: require("../public/assets/coins.jpg"),
    sun: require("../public/assets/sun.svg"),
    plate: require("../public/assets/plate.jpg"),
    facebook: require("../public/assets/facebook.svg"),
    twitter: require("../public/assets/twitter.svg"),
    google: require("../public/assets/google.svg"),
    youtube: require("../public/assets/youtube.svg"),
    question: require("../public/assets/question.svg"),
    first: require("../public/assets/first.png"),
    second: require("../public/assets/second.png"),
    third: require("../public/assets/third.png"),
    purchaseGlobe: require("../public/assets/purchaseglobe.svg"),
    dolphin: require("../public/assets/dolphin.svg"),
    tick: require("../public/assets/tick.svg"),
    mainQuestionMark: require("../public/assets/mainQuestionMark.svg"),
    bell: require("../public/assets/bell.svg"),
    ratio: require("../public/assets/ratio.svg"),
    close: require("../public/assets/close.svg"),
    box: require("../public/assets/box.svg"),
    speaker: require("../public/assets/speaker.svg"),
    alert: require("../public/assets/alert.svg"),
    gift: require("../public/assets/gift.svg"),
    wallet: require("../public/assets/wallet.svg"),
    lamb: require("../public/assets/lamb.svg"),
  };
  